name: veriwork_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  lottie: ^3.3.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/profile_banner.png
    - assets/images/
    - assets/lottie/
    # Lottie files used in the app
    - assets/lottie/Successful Verification.json
    - assets/lottie/Verification Failed.json

  fonts:
    - family: Unbounded
      fonts:
        - asset: assets/fonts/Unbounded-Regular.ttf
        - asset: assets/fonts/Unbounded-Bold.ttf
          weight: 700
